# This is a basic workflow
name: CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm run install:ci

      - name: Run build
        run: npm run package

      - name: Generate .vsix package
        if: runner.os == 'Linux'  
        run: |
          npm install -g @vscode/vsce
          vsce package

      - name: Upload VSIX artifact
        if: runner.os == 'Linux'  
        uses: actions/upload-artifact@v4
        with:
          name: vscode-granite-vsix-${{ runner.os }}-${{ github.run_id }}
          path: "./vscode-granite-*.vsix"

      - name: Run Test
        uses: mcr.microsoft.com/vscode/devcontainers/xvfb-action@latest

      - name: Update latest release
        if: runner.os == 'Linux' && github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.vsix
